### PR TITLE
Normalize path before comparing. Fixes GitbookIO/gitbook#868

### PR DESCRIPTION
**Pull request by gaearon**
If you're OK with taking this, I can try writing a test too.
Original issue: https://github.com/GitbookIO/gitbook/issues/868

### CODE REVIEW

**Comment by gaearon** [comment]
Anything I can do to help get this merged sooner? It's the reason we have this embarrassing TOC in production:

screen shot 2015-09-04 at 16 14 05

**Comment by SamyPesse** [comment]
I'm going to take a look at this PR today. I want to write some tests for it to be sure that it doesn't cause some other bugs.

**Comment by gaearon** [comment]
OK, thanks a lot! And I'm sorry if I sounded demanding or arrogant. I got emotional over this one because I had a local copy with a fix but later jumped to 2.3.0 and forgot about it. If I can help you with this issue, or any other, you have my time—just let me know where I can be helpful.

**Comment by SamyPesse** [comment]
Thanks :+1:

**Comment by SamyPesse** [comment]
But I'm sorry I don't see how it's fixing your issue, according to your message on https://github.com/GitbookIO/gitbook/issues/868, your book:

```
# SUMMARY.md

* [Read me](README.md)
* [Introduction](/docs/introduction/README.md)
  * [Motivation](/docs/introduction/Motivation.md)
  * [Three Principles](/docs/introduction/ThreePrinciples.md)
  * etc

```

your `book.json` is:

```js
{
  "structure": {
    "summary": "docs/README.md"
  }
}
```

But this [line](https://github.com/GitbookIO/gitbook-parsers/blob/master/lib/summary.js#L18) requires the first entry to be the introduction (which is not your case), so your SUMMARY is parsed as:

```
[ { path: 'docs/introduction/README.md',
       title: 'Introduction',
       level: '0',
       articles: [],
       exists: true,
       external: false,
       introduction: true },
     { path: 'README.md',
       title: 'Read me',
       level: '1',
       articles: [],
       exists: true,
       external: false,
       introduction: false },
     { path: 'docs/introduction/README.md',
       title: 'Introduction',
       level: '2',
       articles: [ ... ],
       exists: true,
       external: false,
       introduction: true } ] }
```

**Comment by SamyPesse** [comment]
To make it work for your case, we'll need to remove the condition `First Summary entry is book introduction`.

This can be done by changing the condition (line 15 to 20) to:

```js
    // Check if introduction node was specified in SUMMARY.md
   var hasIntro = _.find(chapterList, function(entry) {
       return normalizePath(entry.path) == normalizePath(options.entryPoint)
    })
    if (hasIntro) {
        return chapterList;
    }
```

**Comment by gaearon** [comment]
>But this line requires the first entry to be the introduction (which is not your case)

Perhaps we misunderstood each other. I don't want my “Introduction” chapter to act as Gitbook's `introduction` page. I want my “introduction” chapter to be a regular chapter, and I want my README to act as Gitbook's `introduction` (but still be called "Read Me"). Does this help?

**Comment by SamyPesse** [comment]
Please run locally:

```
# Clone latest master
$ git clone https://github.com/GitbookIO/gitbook.git ./gitbook
$ npm i ./gitbook

# Link master as version 2.3.0
$ gitbook versions:uninstall 2.3.0
$ gitbook versions:link 2.3.0 ./gitbook

# Build your book with this version
$ gitbook serve ./your-book
```

I tested locally and the output looks good to me, just let me if I'm wrong.

**Comment by gaearon** [comment]
This works great, thank you so much!
Can I help you with other issues?

**Pull request merged**
